# Generated by Django 5.2 on 2025-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='place_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='types',
        ),
        migrations.AddIndex(
            model_name='touristspot',
            index=models.Index(fields=['city', 'rating'], name='pontos_turi_city_62c6c8_idx'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='types',
            field=models.ManyToManyField(to='pontos_turisticos.type'),
        ),
    ]
