# Generated by Django 5.2 on 2025-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0002_type_alter_touristspot_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
