# Generated by Django 5.2 on 2025-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0003_alter_touristspot_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='touristspot',
            name='pontos_turi_city_62c6c8_idx',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='citytype',
            unique_together={('city', 'type')},
        ),
    ]
